# Database Settings
database:
  host: host
  port: 5432
  dbname: "dbname"
  username: "usuername"
  password: "password"
  sslmode: "require"
  connection_timeout: 60
  pool_size: 5
  add_sample_data: true
  connection_string: "postgresql://username:password@host:5432/dbname?sslmode=require&connect_timeout=60&pool_size=5"

# File Paths
paths:
  input_dir: data/input
  output_dir: data/output
  log_dir: logs
  model_dir: models
  template_dir: swift_testing/templates

# Model Settings
model:
  version: "1.0.0"
  prediction_threshold: 0.5
  model_type: "random_forest"
  model_params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  feature_extraction:
    vectorizer: "tfidf"
    max_features: 1000
    ngram_range: [1, 3]

# Logging & Evaluation Settings
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "swift_testing.log"

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  confusion_matrix: true
  cross_validation: 
    enabled: true
    n_splits: 5
  output_format:
    - csv
    - json
    - plot
  plot:
    dpi: 300
    width: 10
    height: 8
    save_format: png 
    
message_generation:
  num_messages: 100
  variation_strategy: "simple"
  variator_config:
    max_variations: 5
    variation_depth: 2